re run
Signed-off-by: Sohaib Manah <souhaibemanah@gmail.com>

diff --git a/nextjs/Dockerfile b/nextjs/Dockerfile
--- a/nextjs/Dockerfile
+++ b/nextjs/Dockerfile
@@ -7,8 +7,13 @@ RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
 # Install dependencies based on the preferred package manager
-COPY package.json package-lock.json*  ./
-RUN npm ci
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 
 # Rebuild the source code only when needed
@@ -22,7 +27,7 @@ COPY . .
 # Uncomment the following line in case you want to disable telemetry during the build.
 # ENV NEXT_TELEMETRY_DISABLED 1
 
-#RUN yarn build
+RUN yarn build
 
 # If using npm comment out above and use below instead
 # RUN npm run build
@@ -52,4 +57,3 @@ EXPOSE 3000
 ENV PORT 3000
 
 CMD ["node", "server.js"]
-
